export const projects = [
    { title: 'Screensaver Generator', 
        date: 'December 2018', 
        img: 'screensaver.jpg',
        tags: ['school', 'processing'],
        desc: 'First ever java-based project created for school.', 
        link: 'https://github.com/MuteMini/ICS2D3-ISP' },
    { title: 'Who Wants To Be A Milionaire', 
        date: 'December 2019', 
        img: 'wwtbam.jpg', 
        tags: ['school', 'java'],
        desc: 'Simple grade eleven project.', 
        link: 'https://github.com/MuteMini/ICS3U3-ISP' },
    { title: 'Validdit', 
        date: 'June 2020', 
        img: 'validdit.jpg', 
        tags: ['hackathon', 'python'],
        desc: 'First ever hackathon project. Gathered experience writing back-end code.', 
        link: 'https://devpost.com/software/validdit-dcfjua' },
    { title: 'Bus Conductor', 
        date: 'June 2020', 
        img: 'busmanager.jpg', 
        tags: ['school', 'java'],
        desc: 'My grade twelve final culminating project. Became comfortable with abstraction and interfacing.', 
        link: 'https://github.com/MuteMini/ICS4U0-ISP' },
    { title: 'Personal Website V.1', 
        date: 'June 2020', 
        img: 'busmanager.jpg', 
        tags: ['school', 'html'],
        desc: 'Simple static website built for school. Was the stepping stone to this website :)', 
        link: 'https://github.com/MuteMini/ICS4U0-ISP' },
    { title: 'SokoSwitch', 
        date: 'July 2020', 
        img: 'sokoswitch.gif', 
        tags: ['game dev', 'java'],
        desc: 'Used past java knowledge to create a personal project using LibGDX.', 
        link: 'https://github.com/MuteMini/Sokoswitch' },
    { title: 'Auricular.ai', 
        date: 'January 2021', 
        img: 'auricular.jpg', 
        tags: ['hackathon', 'python'],
        desc: 'Created for HtN 2020++. Won second for the Facebook API category.', 
        link: 'https://devpost.com/software/auricular-ai' },
    { title: 'HandPong', 
        date: 'September 2021', 
        img: 'handpong.jpg', 
        tags: ['hackathon', 'node.js'],
        desc: 'Created for HtN 2021. Learnt power of modern web app languages.', 
        link: 'https://devpost.com/software/handpong' },
];