export const projects = [
    { title: 'Screensaver Generator', 
        date: 'December 2018', 
        img: 'screensaver.jpg',
        tags: ['school', 'java'],
        desc: '', 
        link: 'https://github.com/MuteMini/ICS2D3-ISP' },
    { title: 'Who Wants To Be A Milionaire', 
        date: 'December 2019', 
        img: 'wwtbam.jpg', 
        tags: ['school', 'java'],
        desc: '', 
        link: 'https://github.com/MuteMini/ICS3U3-ISP' },
    { title: 'Validdit', 
        date: 'June 2020', 
        img: 'validdit.jpg', 
        tags: ['hackathon', 'python'],
        desc: '', 
        link: 'https://devpost.com/software/validdit-dcfjua' },
    { title: 'Bus Conductor', 
        date: 'June 2020', 
        img: 'busmanager.jpg', 
        tags: ['school', 'java'],
        desc: '', 
        link: 'https://github.com/MuteMini/ICS4U0-ISP' },
    { title: 'Personal Website V.1', 
        date: 'June 2020', 
        img: 'busmanager.jpg', 
        tags: ['school', 'html'],
        desc: '', 
        link: 'https://github.com/MuteMini/ICS4U0-ISP' },
    { title: 'SokoSwitch', 
        date: 'July 2020', 
        img: 'sokoswitch.gif', 
        tags: ['game dev', 'java'],
        desc: '', 
        link: 'https://github.com/MuteMini/Sokoswitch' },
    { title: 'Auricular.ai', 
        date: 'January 2021', 
        img: 'auricular.jpg', 
        tags: ['hackaton', 'python'],
        desc: '', 
        link: 'https://devpost.com/software/auricular-ai' },
    { title: 'HandPong', 
        date: 'September 2021', 
        img: 'handpong.jpg', 
        tags: ['hackaton', 'node.js'],
        desc: '', 
        link: 'https://devpost.com/software/handpong' },
];